sample_rate: 30_000

mel_spectrogram:
  # source: [1] 3.1. Feature Extraction
  win_length: 0.031
  hop_length: 0.008
  n_mels: 128
  f_min: 30
  f_max: 16_000

augmentation: 
  reverb:
    p: 0.
  time_shift:
    p: 0.5
  noise:
    p: 0.5
    min_snr_db: 30
    max_snr_db: 1
  dropblock:
    p: 0.5
    dp: 0.5
    block_size:
      t: 32
      f: 4
  time_masking:
    p: 0.5
    tmp: 20
    num: 6
  freq_masking:
    p: 0.5
    fmp: 5
    num: 5
    


pretrain_urban: false

pretrain:
  num_workers: 2

  epochs: 0
  patience: 35
  lr: 0.001
  weight_decay: 0.1
  batch_size: 16
  accum_iter: 4
  grad_clip_value: .0
  grad_clip_norm: 2.0
  use_checkpoint: false 

train:
  num_workers: 2

  patience: 35
  lr: 0.0003
  weight_decay: 0.1
  batch_size: 16
  accum_iter: 4
  grad_clip_value: .5
  grad_clip_norm: .0
  use_checkpoint: false 

model:
  res_block:
    activation: gelu
    batch_first: true
    kernel_size: [5, 5]
    kernel_size_res: [2, 2]

  blocks:
    - res: [32, 32]
    - max_pool: [2, 2]

    - drop: [0.25, 0.25, 8, 4]
    - dropout: 0.15
    - res: [64, 64]
    - max_pool: [2, 2]

    - drop: [0.25, 0.25, 4, 2]
    - dropout: 0.15
    - res: [128, 128]
    - activation: swiglu
    - max_pool: [2, 2]
    

    - drop: [0.25, 0.25, 2, 2]
    - dropout: 0.15
    - res: [256, 256]
    - activation: swiglu
    - max_pool: [2, 2]
    
    - res: [64, 16]
    - pooling:
        mode: avg
        flat: true

    - fc: 256
    - activation: gelu
    - fc: 128
    - activation: gelu